/*
 * This file is generated by jOOQ.
 */
package com.study.module.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Poetry implements Serializable {

    private static final long serialVersionUID = 1854883772;

    private Integer id;
    private Integer poetId;
    private String  title;
    private String  content;

    public Poetry() {}

    public Poetry(Poetry value) {
        this.id = value.id;
        this.poetId = value.poetId;
        this.title = value.title;
        this.content = value.content;
    }

    public Poetry(
        Integer id,
        Integer poetId,
        String  title,
        String  content
    ) {
        this.id = id;
        this.poetId = poetId;
        this.title = title;
        this.content = content;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getPoetId() {
        return this.poetId;
    }

    public void setPoetId(Integer poetId) {
        this.poetId = poetId;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Poetry (");

        sb.append(id);
        sb.append(", ").append(poetId);
        sb.append(", ").append(title);
        sb.append(", ").append(content);

        sb.append(")");
        return sb.toString();
    }
}
