/*
 * This file is generated by jOOQ.
 */
package com.study.module.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 薪资表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TSalary implements Serializable {

    private static final long serialVersionUID = -815770203;

    private Integer       id;
    private String        name;
    private String        position;
    private String        office;
    private Integer       age;
    private LocalDateTime startDate;
    private Integer       salary;

    public TSalary() {}

    public TSalary(TSalary value) {
        this.id = value.id;
        this.name = value.name;
        this.position = value.position;
        this.office = value.office;
        this.age = value.age;
        this.startDate = value.startDate;
        this.salary = value.salary;
    }

    public TSalary(
        Integer       id,
        String        name,
        String        position,
        String        office,
        Integer       age,
        LocalDateTime startDate,
        Integer       salary
    ) {
        this.id = id;
        this.name = name;
        this.position = position;
        this.office = office;
        this.age = age;
        this.startDate = startDate;
        this.salary = salary;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPosition() {
        return this.position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    public String getOffice() {
        return this.office;
    }

    public void setOffice(String office) {
        this.office = office;
    }

    public Integer getAge() {
        return this.age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public LocalDateTime getStartDate() {
        return this.startDate;
    }

    public void setStartDate(LocalDateTime startDate) {
        this.startDate = startDate;
    }

    public Integer getSalary() {
        return this.salary;
    }

    public void setSalary(Integer salary) {
        this.salary = salary;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TSalary (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(position);
        sb.append(", ").append(office);
        sb.append(", ").append(age);
        sb.append(", ").append(startDate);
        sb.append(", ").append(salary);

        sb.append(")");
        return sb.toString();
    }
}
