/*
 * This file is generated by jOOQ.
 */
package com.study.module.jooq.tables.pojos;


import java.io.Serializable;


/**
 * 系统日志表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WebLog implements Serializable {

    private static final long serialVersionUID = -1778161789;

    private Long    id;
    private Integer code;
    private String  description;
    private String  username;
    private Long    startTime;
    private Long    spendTime;
    private String  basePath;
    private String  uri;
    private String  url;
    private String  method;
    private String  ip;
    private String  parameter;
    private String  result;

    public WebLog() {}

    public WebLog(WebLog value) {
        this.id = value.id;
        this.code = value.code;
        this.description = value.description;
        this.username = value.username;
        this.startTime = value.startTime;
        this.spendTime = value.spendTime;
        this.basePath = value.basePath;
        this.uri = value.uri;
        this.url = value.url;
        this.method = value.method;
        this.ip = value.ip;
        this.parameter = value.parameter;
        this.result = value.result;
    }

    public WebLog(
        Long    id,
        Integer code,
        String  description,
        String  username,
        Long    startTime,
        Long    spendTime,
        String  basePath,
        String  uri,
        String  url,
        String  method,
        String  ip,
        String  parameter,
        String  result
    ) {
        this.id = id;
        this.code = code;
        this.description = description;
        this.username = username;
        this.startTime = startTime;
        this.spendTime = spendTime;
        this.basePath = basePath;
        this.uri = uri;
        this.url = url;
        this.method = method;
        this.ip = ip;
        this.parameter = parameter;
        this.result = result;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCode() {
        return this.code;
    }

    public void setCode(Integer code) {
        this.code = code;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Long getStartTime() {
        return this.startTime;
    }

    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    public Long getSpendTime() {
        return this.spendTime;
    }

    public void setSpendTime(Long spendTime) {
        this.spendTime = spendTime;
    }

    public String getBasePath() {
        return this.basePath;
    }

    public void setBasePath(String basePath) {
        this.basePath = basePath;
    }

    public String getUri() {
        return this.uri;
    }

    public void setUri(String uri) {
        this.uri = uri;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getMethod() {
        return this.method;
    }

    public void setMethod(String method) {
        this.method = method;
    }

    public String getIp() {
        return this.ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public String getParameter() {
        return this.parameter;
    }

    public void setParameter(String parameter) {
        this.parameter = parameter;
    }

    public String getResult() {
        return this.result;
    }

    public void setResult(String result) {
        this.result = result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WebLog (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(description);
        sb.append(", ").append(username);
        sb.append(", ").append(startTime);
        sb.append(", ").append(spendTime);
        sb.append(", ").append(basePath);
        sb.append(", ").append(uri);
        sb.append(", ").append(url);
        sb.append(", ").append(method);
        sb.append(", ").append(ip);
        sb.append(", ").append(parameter);
        sb.append(", ").append(result);

        sb.append(")");
        return sb.toString();
    }
}
