server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zero?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 标识逻辑删除了
      logic-not-delete-value: 0 # 未被逻辑的标识
logging:
  level:
    com.jiangfeixiang.mpdemo.springbootmp.mapper: debug
