/*
 Navicat Premium Data Transfer

 Source Server         : orcl-localhost-zl
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : localhost:1521
 Source Schema         : ZHONGZERO

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 10/05/2020 00:47:22
*/


-- ----------------------------
-- Table structure for SALARY
-- ----------------------------
DROP TABLE "ZHONGZERO"."SALARY";
CREATE TABLE "ZHONGZERO"."SALARY" (
  "ID" NVARCHAR2(64) NOT NULL ,
  "PROC_INS_ID" NVARCHAR2(64) ,
  "USER_ID" NVARCHAR2(64) ,
  "OFFICE_ID" NVARCHAR2(64) ,
  "POST" NVARCHAR2(255) ,
  "AGE" NCHAR(1) ,
  "EDU" NVARCHAR2(255) ,
  "CONTENT" NVARCHAR2(255) ,
  "OLDA" NVARCHAR2(255) ,
  "OLDB" NVARCHAR2(255) ,
  "OLDC" NVARCHAR2(255) ,
  "NEWA" NVARCHAR2(255) ,
  "NEWB" NVARCHAR2(255) ,
  "NEWC" NVARCHAR2(255) ,
  "ADD_NUM" NVARCHAR2(255) ,
  "EXE_DATE" NVARCHAR2(255) ,
  "HR_TEXT" NVARCHAR2(255) ,
  "LEAD_TEXT" NVARCHAR2(255) ,
  "MAIN_LEAD_TEXT" NVARCHAR2(255) ,
  "CREATE_BY" NVARCHAR2(64) NOT NULL ,
  "CREATE_DATE" DATE NOT NULL ,
  "UPDATE_BY" NVARCHAR2(64) NOT NULL ,
  "UPDATE_DATE" DATE NOT NULL ,
  "REMARKS" NVARCHAR2(255) ,
  "DEL_FLAG" NCHAR(1) NOT NULL 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "ZHONGZERO"."SALARY"."ID" IS '编号';
COMMENT ON COLUMN "ZHONGZERO"."SALARY"."PROC_INS_ID" IS '流程实例ID';
COMMENT ON COLUMN "ZHONGZERO"."SALARY"."USER_ID" IS '变动用户';
COMMENT ON COLUMN "ZHONGZERO"."SALARY"."OFFICE_ID" IS '归属部门';
COMMENT ON COLUMN "ZHONGZERO"."SALARY"."POST" IS '岗位';
COMMENT ON COLUMN "ZHONGZERO"."SALARY"."AGE" IS '性别';
COMMENT ON COLUMN "ZHONGZERO"."SALARY"."EDU" IS '学历';
COMMENT ON COLUMN "ZHONGZERO"."SALARY"."CONTENT" IS '调整原因';
COMMENT ON COLUMN "ZHONGZERO"."SALARY"."OLDA" IS '现行标准 薪酬档级';
COMMENT ON COLUMN "ZHONGZERO"."SALARY"."OLDB" IS '现行标准 月工资额';
COMMENT ON COLUMN "ZHONGZERO"."SALARY"."OLDC" IS '现行标准 年薪总额';
COMMENT ON COLUMN "ZHONGZERO"."SALARY"."NEWA" IS '调整后标准 薪酬档级';
COMMENT ON COLUMN "ZHONGZERO"."SALARY"."NEWB" IS '调整后标准 月工资额';
COMMENT ON COLUMN "ZHONGZERO"."SALARY"."NEWC" IS '调整后标准 年薪总额';
COMMENT ON COLUMN "ZHONGZERO"."SALARY"."ADD_NUM" IS '月增资';
COMMENT ON COLUMN "ZHONGZERO"."SALARY"."EXE_DATE" IS '执行时间';
COMMENT ON COLUMN "ZHONGZERO"."SALARY"."HR_TEXT" IS '人力资源部门意见';
COMMENT ON COLUMN "ZHONGZERO"."SALARY"."LEAD_TEXT" IS '分管领导意见';
COMMENT ON COLUMN "ZHONGZERO"."SALARY"."MAIN_LEAD_TEXT" IS '集团主要领导意见';
COMMENT ON COLUMN "ZHONGZERO"."SALARY"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "ZHONGZERO"."SALARY"."CREATE_DATE" IS '创建时间';
COMMENT ON COLUMN "ZHONGZERO"."SALARY"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "ZHONGZERO"."SALARY"."UPDATE_DATE" IS '更新时间';
COMMENT ON COLUMN "ZHONGZERO"."SALARY"."REMARKS" IS '备注信息';
COMMENT ON COLUMN "ZHONGZERO"."SALARY"."DEL_FLAG" IS '删除标记';
COMMENT ON TABLE "ZHONGZERO"."SALARY" IS '审批流程测试表';

-- ----------------------------
-- Records of "SALARY"
-- ----------------------------
INSERT INTO "ZHONGZERO"."SALARY" VALUES ('825693cd6c1c4f6b86699fc3f1a54887', NULL, '136', NULL, NULL, NULL, NULL, '技能提高', NULL, NULL, NULL, NULL, '100', NULL, NULL, NULL, '同意', '同意', '总经理审批', '1', TO_DATE('2017-12-15 22:01:41', 'SYYYY-MM-DD HH24:MI:SS'), '1', TO_DATE('2017-12-15 22:01:41', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '1');

-- ----------------------------
-- Primary Key structure for table SALARY
-- ----------------------------
ALTER TABLE "ZHONGZERO"."SALARY" ADD CONSTRAINT "SYS_C0023819" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table SALARY
-- ----------------------------
ALTER TABLE "ZHONGZERO"."SALARY" ADD CONSTRAINT "SYS_C0023801" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZHONGZERO"."SALARY" ADD CONSTRAINT "SYS_C0023802" CHECK ("CREATE_BY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZHONGZERO"."SALARY" ADD CONSTRAINT "SYS_C0023803" CHECK ("CREATE_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZHONGZERO"."SALARY" ADD CONSTRAINT "SYS_C0023804" CHECK ("UPDATE_BY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZHONGZERO"."SALARY" ADD CONSTRAINT "SYS_C0023805" CHECK ("UPDATE_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZHONGZERO"."SALARY" ADD CONSTRAINT "SYS_C0023806" CHECK ("DEL_FLAG" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
