spring:
  application:
    name: config-client
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-client
  profiles:
    active: dev
server:
  port: 8762
eureka:
  client:
    service-url:
      defautlZone: http://localhost:8761/eureka/