/*
 * This file is generated by jOOQ.
 */
package com.study.module.jooq.tables.daos;


import com.study.module.jooq.tables.WebLog;
import com.study.module.jooq.tables.records.WebLogRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 系统日志表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WebLogDao extends DAOImpl<WebLogRecord, com.study.module.jooq.tables.pojos.WebLog, Long> {

    /**
     * Create a new WebLogDao without any configuration
     */
    public WebLogDao() {
        super(WebLog.WEB_LOG, com.study.module.jooq.tables.pojos.WebLog.class);
    }

    /**
     * Create a new WebLogDao with an attached configuration
     */
    public WebLogDao(Configuration configuration) {
        super(WebLog.WEB_LOG, com.study.module.jooq.tables.pojos.WebLog.class, configuration);
    }

    @Override
    public Long getId(com.study.module.jooq.tables.pojos.WebLog object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.study.module.jooq.tables.pojos.WebLog> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(WebLog.WEB_LOG.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.study.module.jooq.tables.pojos.WebLog> fetchById(Long... values) {
        return fetch(WebLog.WEB_LOG.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.study.module.jooq.tables.pojos.WebLog fetchOneById(Long value) {
        return fetchOne(WebLog.WEB_LOG.ID, value);
    }

    /**
     * Fetch records that have <code>code BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.study.module.jooq.tables.pojos.WebLog> fetchRangeOfCode(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(WebLog.WEB_LOG.CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>code IN (values)</code>
     */
    public List<com.study.module.jooq.tables.pojos.WebLog> fetchByCode(Integer... values) {
        return fetch(WebLog.WEB_LOG.CODE, values);
    }

    /**
     * Fetch records that have <code>description BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.study.module.jooq.tables.pojos.WebLog> fetchRangeOfDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(WebLog.WEB_LOG.DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.study.module.jooq.tables.pojos.WebLog> fetchByDescription(String... values) {
        return fetch(WebLog.WEB_LOG.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>username BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.study.module.jooq.tables.pojos.WebLog> fetchRangeOfUsername(String lowerInclusive, String upperInclusive) {
        return fetchRange(WebLog.WEB_LOG.USERNAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<com.study.module.jooq.tables.pojos.WebLog> fetchByUsername(String... values) {
        return fetch(WebLog.WEB_LOG.USERNAME, values);
    }

    /**
     * Fetch records that have <code>start_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.study.module.jooq.tables.pojos.WebLog> fetchRangeOfStartTime(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(WebLog.WEB_LOG.START_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>start_time IN (values)</code>
     */
    public List<com.study.module.jooq.tables.pojos.WebLog> fetchByStartTime(Long... values) {
        return fetch(WebLog.WEB_LOG.START_TIME, values);
    }

    /**
     * Fetch records that have <code>spend_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.study.module.jooq.tables.pojos.WebLog> fetchRangeOfSpendTime(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(WebLog.WEB_LOG.SPEND_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>spend_time IN (values)</code>
     */
    public List<com.study.module.jooq.tables.pojos.WebLog> fetchBySpendTime(Long... values) {
        return fetch(WebLog.WEB_LOG.SPEND_TIME, values);
    }

    /**
     * Fetch records that have <code>base_path BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.study.module.jooq.tables.pojos.WebLog> fetchRangeOfBasePath(String lowerInclusive, String upperInclusive) {
        return fetchRange(WebLog.WEB_LOG.BASE_PATH, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>base_path IN (values)</code>
     */
    public List<com.study.module.jooq.tables.pojos.WebLog> fetchByBasePath(String... values) {
        return fetch(WebLog.WEB_LOG.BASE_PATH, values);
    }

    /**
     * Fetch records that have <code>uri BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.study.module.jooq.tables.pojos.WebLog> fetchRangeOfUri(String lowerInclusive, String upperInclusive) {
        return fetchRange(WebLog.WEB_LOG.URI, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>uri IN (values)</code>
     */
    public List<com.study.module.jooq.tables.pojos.WebLog> fetchByUri(String... values) {
        return fetch(WebLog.WEB_LOG.URI, values);
    }

    /**
     * Fetch records that have <code>url BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.study.module.jooq.tables.pojos.WebLog> fetchRangeOfUrl(String lowerInclusive, String upperInclusive) {
        return fetchRange(WebLog.WEB_LOG.URL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>url IN (values)</code>
     */
    public List<com.study.module.jooq.tables.pojos.WebLog> fetchByUrl(String... values) {
        return fetch(WebLog.WEB_LOG.URL, values);
    }

    /**
     * Fetch records that have <code>method BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.study.module.jooq.tables.pojos.WebLog> fetchRangeOfMethod(String lowerInclusive, String upperInclusive) {
        return fetchRange(WebLog.WEB_LOG.METHOD, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>method IN (values)</code>
     */
    public List<com.study.module.jooq.tables.pojos.WebLog> fetchByMethod(String... values) {
        return fetch(WebLog.WEB_LOG.METHOD, values);
    }

    /**
     * Fetch records that have <code>ip BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.study.module.jooq.tables.pojos.WebLog> fetchRangeOfIp(String lowerInclusive, String upperInclusive) {
        return fetchRange(WebLog.WEB_LOG.IP, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ip IN (values)</code>
     */
    public List<com.study.module.jooq.tables.pojos.WebLog> fetchByIp(String... values) {
        return fetch(WebLog.WEB_LOG.IP, values);
    }

    /**
     * Fetch records that have <code>parameter BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.study.module.jooq.tables.pojos.WebLog> fetchRangeOfParameter(String lowerInclusive, String upperInclusive) {
        return fetchRange(WebLog.WEB_LOG.PARAMETER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>parameter IN (values)</code>
     */
    public List<com.study.module.jooq.tables.pojos.WebLog> fetchByParameter(String... values) {
        return fetch(WebLog.WEB_LOG.PARAMETER, values);
    }

    /**
     * Fetch records that have <code>result BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.study.module.jooq.tables.pojos.WebLog> fetchRangeOfResult(String lowerInclusive, String upperInclusive) {
        return fetchRange(WebLog.WEB_LOG.RESULT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>result IN (values)</code>
     */
    public List<com.study.module.jooq.tables.pojos.WebLog> fetchByResult(String... values) {
        return fetch(WebLog.WEB_LOG.RESULT, values);
    }
}
