/*
 * This file is generated by jOOQ.
 */
package com.study.module.jooq.tables.records;


import com.study.module.jooq.tables.TSalary;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 薪资表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TSalaryRecord extends UpdatableRecordImpl<TSalaryRecord> implements Record7<Integer, String, String, String, Integer, LocalDateTime, Integer> {

    private static final long serialVersionUID = -552915287;

    /**
     * Setter for <code>zero.t_salary.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>zero.t_salary.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>zero.t_salary.name</code>. 员工姓名
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>zero.t_salary.name</code>. 员工姓名
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>zero.t_salary.position</code>. 职位
     */
    public void setPosition(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>zero.t_salary.position</code>. 职位
     */
    public String getPosition() {
        return (String) get(2);
    }

    /**
     * Setter for <code>zero.t_salary.office</code>. 办公地点
     */
    public void setOffice(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>zero.t_salary.office</code>. 办公地点
     */
    public String getOffice() {
        return (String) get(3);
    }

    /**
     * Setter for <code>zero.t_salary.age</code>. 年龄
     */
    public void setAge(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>zero.t_salary.age</code>. 年龄
     */
    public Integer getAge() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>zero.t_salary.start_date</code>. 入职日期

     */
    public void setStartDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>zero.t_salary.start_date</code>. 入职日期

     */
    public LocalDateTime getStartDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>zero.t_salary.salary</code>. 薪水
     */
    public void setSalary(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>zero.t_salary.salary</code>. 薪水
     */
    public Integer getSalary() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, Integer, LocalDateTime, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, String, Integer, LocalDateTime, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TSalary.T_SALARY.ID;
    }

    @Override
    public Field<String> field2() {
        return TSalary.T_SALARY.NAME;
    }

    @Override
    public Field<String> field3() {
        return TSalary.T_SALARY.POSITION;
    }

    @Override
    public Field<String> field4() {
        return TSalary.T_SALARY.OFFICE;
    }

    @Override
    public Field<Integer> field5() {
        return TSalary.T_SALARY.AGE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return TSalary.T_SALARY.START_DATE;
    }

    @Override
    public Field<Integer> field7() {
        return TSalary.T_SALARY.SALARY;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getPosition();
    }

    @Override
    public String component4() {
        return getOffice();
    }

    @Override
    public Integer component5() {
        return getAge();
    }

    @Override
    public LocalDateTime component6() {
        return getStartDate();
    }

    @Override
    public Integer component7() {
        return getSalary();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getPosition();
    }

    @Override
    public String value4() {
        return getOffice();
    }

    @Override
    public Integer value5() {
        return getAge();
    }

    @Override
    public LocalDateTime value6() {
        return getStartDate();
    }

    @Override
    public Integer value7() {
        return getSalary();
    }

    @Override
    public TSalaryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TSalaryRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public TSalaryRecord value3(String value) {
        setPosition(value);
        return this;
    }

    @Override
    public TSalaryRecord value4(String value) {
        setOffice(value);
        return this;
    }

    @Override
    public TSalaryRecord value5(Integer value) {
        setAge(value);
        return this;
    }

    @Override
    public TSalaryRecord value6(LocalDateTime value) {
        setStartDate(value);
        return this;
    }

    @Override
    public TSalaryRecord value7(Integer value) {
        setSalary(value);
        return this;
    }

    @Override
    public TSalaryRecord values(Integer value1, String value2, String value3, String value4, Integer value5, LocalDateTime value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TSalaryRecord
     */
    public TSalaryRecord() {
        super(TSalary.T_SALARY);
    }

    /**
     * Create a detached, initialised TSalaryRecord
     */
    public TSalaryRecord(Integer id, String name, String position, String office, Integer age, LocalDateTime startDate, Integer salary) {
        super(TSalary.T_SALARY);

        set(0, id);
        set(1, name);
        set(2, position);
        set(3, office);
        set(4, age);
        set(5, startDate);
        set(6, salary);
    }
}
