/*
 * This file is generated by jOOQ.
 */
package com.study.module.jooq.tables.records;


import com.study.module.jooq.tables.WebLog;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 系统日志表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WebLogRecord extends UpdatableRecordImpl<WebLogRecord> implements Record13<Long, Integer, String, String, Long, Long, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -1129692535;

    /**
     * Setter for <code>zero.web_log.id</code>. 唯一标识
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>zero.web_log.id</code>. 唯一标识
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>zero.web_log.code</code>. 请求状态码（例如：200,500,404等）
     */
    public void setCode(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>zero.web_log.code</code>. 请求状态码（例如：200,500,404等）
     */
    public Integer getCode() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>zero.web_log.description</code>. 操作描述
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>zero.web_log.description</code>. 操作描述
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>zero.web_log.username</code>. 操作用户
     */
    public void setUsername(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>zero.web_log.username</code>. 操作用户
     */
    public String getUsername() {
        return (String) get(3);
    }

    /**
     * Setter for <code>zero.web_log.start_time</code>. 操作时间
     */
    public void setStartTime(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>zero.web_log.start_time</code>. 操作时间
     */
    public Long getStartTime() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>zero.web_log.spend_time</code>. 消耗时间（毫秒）
     */
    public void setSpendTime(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>zero.web_log.spend_time</code>. 消耗时间（毫秒）
     */
    public Long getSpendTime() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>zero.web_log.base_path</code>. 根路径
     */
    public void setBasePath(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>zero.web_log.base_path</code>. 根路径
     */
    public String getBasePath() {
        return (String) get(6);
    }

    /**
     * Setter for <code>zero.web_log.uri</code>. URI
     */
    public void setUri(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>zero.web_log.uri</code>. URI
     */
    public String getUri() {
        return (String) get(7);
    }

    /**
     * Setter for <code>zero.web_log.url</code>. URL
     */
    public void setUrl(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>zero.web_log.url</code>. URL
     */
    public String getUrl() {
        return (String) get(8);
    }

    /**
     * Setter for <code>zero.web_log.method</code>. 请求类型
     */
    public void setMethod(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>zero.web_log.method</code>. 请求类型
     */
    public String getMethod() {
        return (String) get(9);
    }

    /**
     * Setter for <code>zero.web_log.ip</code>. IP地址
     */
    public void setIp(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>zero.web_log.ip</code>. IP地址
     */
    public String getIp() {
        return (String) get(10);
    }

    /**
     * Setter for <code>zero.web_log.parameter</code>. 请求参数
     */
    public void setParameter(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>zero.web_log.parameter</code>. 请求参数
     */
    public String getParameter() {
        return (String) get(11);
    }

    /**
     * Setter for <code>zero.web_log.result</code>. 请求返回的结果
     */
    public void setResult(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>zero.web_log.result</code>. 请求返回的结果
     */
    public String getResult() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, Integer, String, String, Long, Long, String, String, String, String, String, String, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Long, Integer, String, String, Long, Long, String, String, String, String, String, String, String> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return WebLog.WEB_LOG.ID;
    }

    @Override
    public Field<Integer> field2() {
        return WebLog.WEB_LOG.CODE;
    }

    @Override
    public Field<String> field3() {
        return WebLog.WEB_LOG.DESCRIPTION;
    }

    @Override
    public Field<String> field4() {
        return WebLog.WEB_LOG.USERNAME;
    }

    @Override
    public Field<Long> field5() {
        return WebLog.WEB_LOG.START_TIME;
    }

    @Override
    public Field<Long> field6() {
        return WebLog.WEB_LOG.SPEND_TIME;
    }

    @Override
    public Field<String> field7() {
        return WebLog.WEB_LOG.BASE_PATH;
    }

    @Override
    public Field<String> field8() {
        return WebLog.WEB_LOG.URI;
    }

    @Override
    public Field<String> field9() {
        return WebLog.WEB_LOG.URL;
    }

    @Override
    public Field<String> field10() {
        return WebLog.WEB_LOG.METHOD;
    }

    @Override
    public Field<String> field11() {
        return WebLog.WEB_LOG.IP;
    }

    @Override
    public Field<String> field12() {
        return WebLog.WEB_LOG.PARAMETER;
    }

    @Override
    public Field<String> field13() {
        return WebLog.WEB_LOG.RESULT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getCode();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public String component4() {
        return getUsername();
    }

    @Override
    public Long component5() {
        return getStartTime();
    }

    @Override
    public Long component6() {
        return getSpendTime();
    }

    @Override
    public String component7() {
        return getBasePath();
    }

    @Override
    public String component8() {
        return getUri();
    }

    @Override
    public String component9() {
        return getUrl();
    }

    @Override
    public String component10() {
        return getMethod();
    }

    @Override
    public String component11() {
        return getIp();
    }

    @Override
    public String component12() {
        return getParameter();
    }

    @Override
    public String component13() {
        return getResult();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getCode();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public String value4() {
        return getUsername();
    }

    @Override
    public Long value5() {
        return getStartTime();
    }

    @Override
    public Long value6() {
        return getSpendTime();
    }

    @Override
    public String value7() {
        return getBasePath();
    }

    @Override
    public String value8() {
        return getUri();
    }

    @Override
    public String value9() {
        return getUrl();
    }

    @Override
    public String value10() {
        return getMethod();
    }

    @Override
    public String value11() {
        return getIp();
    }

    @Override
    public String value12() {
        return getParameter();
    }

    @Override
    public String value13() {
        return getResult();
    }

    @Override
    public WebLogRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public WebLogRecord value2(Integer value) {
        setCode(value);
        return this;
    }

    @Override
    public WebLogRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public WebLogRecord value4(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public WebLogRecord value5(Long value) {
        setStartTime(value);
        return this;
    }

    @Override
    public WebLogRecord value6(Long value) {
        setSpendTime(value);
        return this;
    }

    @Override
    public WebLogRecord value7(String value) {
        setBasePath(value);
        return this;
    }

    @Override
    public WebLogRecord value8(String value) {
        setUri(value);
        return this;
    }

    @Override
    public WebLogRecord value9(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public WebLogRecord value10(String value) {
        setMethod(value);
        return this;
    }

    @Override
    public WebLogRecord value11(String value) {
        setIp(value);
        return this;
    }

    @Override
    public WebLogRecord value12(String value) {
        setParameter(value);
        return this;
    }

    @Override
    public WebLogRecord value13(String value) {
        setResult(value);
        return this;
    }

    @Override
    public WebLogRecord values(Long value1, Integer value2, String value3, String value4, Long value5, Long value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WebLogRecord
     */
    public WebLogRecord() {
        super(WebLog.WEB_LOG);
    }

    /**
     * Create a detached, initialised WebLogRecord
     */
    public WebLogRecord(Long id, Integer code, String description, String username, Long startTime, Long spendTime, String basePath, String uri, String url, String method, String ip, String parameter, String result) {
        super(WebLog.WEB_LOG);

        set(0, id);
        set(1, code);
        set(2, description);
        set(3, username);
        set(4, startTime);
        set(5, spendTime);
        set(6, basePath);
        set(7, uri);
        set(8, url);
        set(9, method);
        set(10, ip);
        set(11, parameter);
        set(12, result);
    }
}
