server:
  port: 8089
spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    charset: UTF-8
    suffix: .ftl
    content-type: text/html; charset=utf-8
    template-loader-path: classpath:/templates
  mvc:
    servlet:
      path: /
    static-path-pattern: /**
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zero?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml
  typeAliasesPackage: com.study.module.mybatis.entity
  # 开启 mybatis 查询的日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 配置 pageHelper分页插件
pagehelper:
  # 自动检测数据库类型：MySQL
  helper-dialect: mysql
  # 是否启用分页合理化：如果启用，当pagenum<1时，会自动查询第一页的数据，当pagenum>pages时，自动查询最后一页数据；
  # 不启用的，以上两种情况都会返回空数据
  reasonable: true
  #为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值，
  # 可以配置pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射的用默认值，
  # 默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero
  params: count=countSql;pageNum=currentPage;pageSize=pageCount;reasonable=reasonable;pageSizeZero=pageSizeZero
  # 默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  support-methods-arguments: true
  #如果 pageSize=0 就会查询出全部的结果（相当于没有执行分页查询）
  page-size-zero: true