/*
 * This file is generated by jOOQ.
 */
package com.study.module.springbootjooq.generate.routines;


import com.study.module.springbootjooq.generate.Zero;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShowStuName extends AbstractRoutine<String> {

    private static final long serialVersionUID = 67153065;

    /**
     * The parameter <code>zero.show_stu_name.RETURN_VALUE</code>.
     */
    public static final Parameter<String> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.VARCHAR(20), false, false);

    /**
     * The parameter <code>zero.show_stu_name.stu_id1</code>.
     */
    public static final Parameter<Integer> STU_ID1 = Internal.createParameter("stu_id1", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public ShowStuName() {
        super("show_stu_name", Zero.ZERO, org.jooq.impl.SQLDataType.VARCHAR(20));

        setReturnParameter(RETURN_VALUE);
        addInParameter(STU_ID1);
    }

    /**
     * Set the <code>stu_id1</code> parameter IN value to the routine
     */
    public void setStuId1(Integer value) {
        setValue(STU_ID1, value);
    }

    /**
     * Set the <code>stu_id1</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setStuId1(Field<Integer> field) {
        setField(STU_ID1, field);
    }
}
