/*
 * This file is generated by jOOQ.
 */
package com.study.module.springbootjooq.generate.routines;


import com.study.module.springbootjooq.generate.Zero;

import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShowStudent extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 750324041;

    /**
     * Create a new routine call instance
     */
    public ShowStudent() {
        super("show_student", Zero.ZERO);
    }
}
