/*
 * This file is generated by jOOQ.
 */
package com.study.module.springbootjooq.generate.tables.records;


import com.study.module.springbootjooq.generate.tables.Poet;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PoetRecord extends UpdatableRecordImpl<PoetRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -157782536;

    /**
     * Setter for <code>zero.poet.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>zero.poet.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>zero.poet.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>zero.poet.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Poet.POET.ID;
    }

    @Override
    public Field<String> field2() {
        return Poet.POET.NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public PoetRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PoetRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public PoetRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PoetRecord
     */
    public PoetRecord() {
        super(Poet.POET);
    }

    /**
     * Create a detached, initialised PoetRecord
     */
    public PoetRecord(Integer id, String name) {
        super(Poet.POET);

        set(0, id);
        set(1, name);
    }
}
