server:
  port: 8080
spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zero?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat,wall,log4j # druid监控配置
    dbcp2:
      min-idle: 5 # 数据库连接池的最小维持连接数
      initial-size: 5 # 初始化提供的连接数
      max-total: 5 # 最大的连接数
      max-wait-millis: 200 # 等待连接获取的最大超时时间
#sqlhelper:
#  mybatis:
#    mapper-locations: classpath:/mapper/*Dao.xml
#    count: true
#    countSuffix: _COUNT
#    defaultPageSize: 10
#    instrumentor:
#      cacheInstrumentedSql: true
#      dialect: mysql
#      subqueryPagingEndFlag: '[PAGING_END]'
#      subqueryPagingStartFlag: '[PAGING_START]'
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.example.demo.dao
  mapper-locations:  classpath:/mapper/*Dao.xml