/*
 * This file is generated by jOOQ.
 */
package edu.study.module.springbootjooq.generate;


import edu.study.module.springbootjooq.generate.tables.PdmanDbVersion;
import edu.study.module.springbootjooq.generate.tables.Poet;
import edu.study.module.springbootjooq.generate.tables.Poetry;
import edu.study.module.springbootjooq.generate.tables.Student;
import edu.study.module.springbootjooq.generate.tables.TSalary;
import edu.study.module.springbootjooq.generate.tables.User;
import edu.study.module.springbootjooq.generate.tables.WebLog;


/**
 * Convenience access to all tables in zero
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>zero.pdman_db_version</code>.
     */
    public static final PdmanDbVersion PDMAN_DB_VERSION = PdmanDbVersion.PDMAN_DB_VERSION;

    /**
     * The table <code>zero.poet</code>.
     */
    public static final Poet POET = Poet.POET;

    /**
     * The table <code>zero.poetry</code>.
     */
    public static final Poetry POETRY = Poetry.POETRY;

    /**
     * The table <code>zero.student</code>.
     */
    public static final Student STUDENT = Student.STUDENT;

    /**
     * 薪资表
     */
    public static final TSalary T_SALARY = TSalary.T_SALARY;

    /**
     * 用户表
     */
    public static final User USER = User.USER;

    /**
     * 系统日志表
     */
    public static final WebLog WEB_LOG = WebLog.WEB_LOG;
}
