server:
  port: 8768
spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:8769
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always