/*
 * This file is generated by jOOQ.
 */
package edu.study.module.springbootjooq.generate.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PdmanDbVersion implements Serializable {

    private static final long serialVersionUID = 1231077207;

    private String dbVersion;
    private String versionDesc;
    private String createdTime;

    public PdmanDbVersion() {}

    public PdmanDbVersion(PdmanDbVersion value) {
        this.dbVersion = value.dbVersion;
        this.versionDesc = value.versionDesc;
        this.createdTime = value.createdTime;
    }

    public PdmanDbVersion(
        String dbVersion,
        String versionDesc,
        String createdTime
    ) {
        this.dbVersion = dbVersion;
        this.versionDesc = versionDesc;
        this.createdTime = createdTime;
    }

    public String getDbVersion() {
        return this.dbVersion;
    }

    public void setDbVersion(String dbVersion) {
        this.dbVersion = dbVersion;
    }

    public String getVersionDesc() {
        return this.versionDesc;
    }

    public void setVersionDesc(String versionDesc) {
        this.versionDesc = versionDesc;
    }

    public String getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PdmanDbVersion (");

        sb.append(dbVersion);
        sb.append(", ").append(versionDesc);
        sb.append(", ").append(createdTime);

        sb.append(")");
        return sb.toString();
    }
}
