/*
 * This file is generated by jOOQ.
 */
package edu.study.module.springbootjooq.generate.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Poet implements Serializable {

    private static final long serialVersionUID = -6758617;

    private Integer id;
    private String  name;

    public Poet() {}

    public Poet(Poet value) {
        this.id = value.id;
        this.name = value.name;
    }

    public Poet(
        Integer id,
        String  name
    ) {
        this.id = id;
        this.name = name;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Poet (");

        sb.append(id);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
