/*
 * This file is generated by jOOQ.
 */
package edu.study.module.springbootjooq.generate.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Student implements Serializable {

    private static final long serialVersionUID = 392223529;

    private Integer stuId;
    private String  stuName;
    private Integer stuAge;
    private String  stuSex;
    private Integer deleted;

    public Student() {}

    public Student(Student value) {
        this.stuId = value.stuId;
        this.stuName = value.stuName;
        this.stuAge = value.stuAge;
        this.stuSex = value.stuSex;
        this.deleted = value.deleted;
    }

    public Student(
        Integer stuId,
        String  stuName,
        Integer stuAge,
        String  stuSex,
        Integer deleted
    ) {
        this.stuId = stuId;
        this.stuName = stuName;
        this.stuAge = stuAge;
        this.stuSex = stuSex;
        this.deleted = deleted;
    }

    public Integer getStuId() {
        return this.stuId;
    }

    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    public String getStuName() {
        return this.stuName;
    }

    public void setStuName(String stuName) {
        this.stuName = stuName;
    }

    public Integer getStuAge() {
        return this.stuAge;
    }

    public void setStuAge(Integer stuAge) {
        this.stuAge = stuAge;
    }

    public String getStuSex() {
        return this.stuSex;
    }

    public void setStuSex(String stuSex) {
        this.stuSex = stuSex;
    }

    public Integer getDeleted() {
        return this.deleted;
    }

    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Student (");

        sb.append(stuId);
        sb.append(", ").append(stuName);
        sb.append(", ").append(stuAge);
        sb.append(", ").append(stuSex);
        sb.append(", ").append(deleted);

        sb.append(")");
        return sb.toString();
    }
}
