server:
  port: 8769
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/config-jdbc?userUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    config:
      label: master # label为git仓库的分支名，此处从主干分支
      server:
        jdbc:
          sql: SELECT key1, value1 from config_properties where APPLICATION=? and PROFILE=? and LABEL=?
#        git:
#          uri: https://github.com/GitSuperDrew/SpringBootDemo  # 远程的clone的地址
#          search-paths: tree/master/eureka/config-server
#          username: GitSuperDrew  # Git 仓库的登录用户名
#          password:   # Git 仓库的登录密码（公开的仓库，所以无需要密码）
#        native:
#          search-locations: classpath:/shared
  profiles:
    active: jdbc
  application:
    name: config-jdbc-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/