server:
  port: 8769
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GitSuperDrew/SpringBootDemo  # 远程的clone的地址
          search-paths: tree/master/eureka/config-server
          username: GitSuperDrew  # Git 仓库的登录用户名
          password:   # Git 仓库的登录密码（公开的仓库，所以无需要密码）
        native:
          search-locations: classpath:/shared
      label: master # label为git仓库的分支名，此处从主干分支
  profiles:
    active: native
  application:
    name: config-server
